remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: Wanjiku Caroline
description: Welcome to my technical happy place

github:
  zip_url: http://example.com/download.zip
  another_url: another value
  repository_name: wanjiku-carol
  project_tagline: Software Engineer | Cybersecurity Analyst
  repository_url: https://github.com/wanjiku-carol/wanjiku-carol
